name: Automate main.py script

on:
  schedule:
    - cron: '0 9 * * *'  # Daily at 2:30 PM SLT
  workflow_dispatch: 

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pdfplumber pandas

    # Step 4: Run the main.py script to download and extract data
    - name: Run main.py script
      run: python main.py
